#!/usr/bin/env bash
set -euo pipefail

build_dir="$(pwd)/out"

usage()
{
    echo "Commands: test [name], debug, clean"
}

make_all()
{
    cmake -S . -B "${build_dir}" -DCMAKE_BUILD_TYPE="Debug"
    cmake --build "${build_dir}" -- all
}

if [ -n "${1+x}" ]; then
    case "$1" in
        "test")
            if [ -z "${2+x}" ]; then
                echo "Error: Test requires a test name as a second argument."
                echo ""
                exit 1
            fi

            echo ">> Building <<"
            make_all
            echo ""

            if [ "$2" == "all" ]; then
                for file in ${build_dir}/bin/*
                do
                    echo ">> Running $(basename $file) test <<"
                    $file
                    echo ""
                done
            else
                test_bin="${build_dir}/bin/${2}"
                if [ ! -f "$test_bin" ]; then
                    echo "ERROR: The executable ${test_bin} was not found."
                    echo ""
                    exit 1
                fi

                echo ">> Running ${2} test <<"
                $test_bin
                echo ""
            fi
            ;;
        "debug")
            echo ">> Building <<"
            make_all
            echo ""
            ;;
        "clean")
            echo ">> Cleaning <<"
            rm -rf "${build_dir}"
            echo "Removed ${build_dir}"
            echo ""
            ;;
        *)
            usage
            ;;
    esac
else
    usage
fi
