#!/usr/bin/env bash
set -euo pipefail

base_dir="$(pwd)"
build_dir="$base_dir/out"
app_name="common"

usage () {
    echo "Commands: test, debug, release, (sudo) install, run, clean"
}

make_all () {
    release="Debug"
    if [ -n "${1+x}" ]; then
        release="$1"
    fi

    cmake -S . -B "${build_dir}" -DCMAKE_BUILD_TYPE="${release}"
    cmake --build "${build_dir}" -- all
}

make_clean () {
    echo ">> Cleaning ${app_name} <<"
    rm -rf "${build_dir}"
    echo "Removed ${build_dir}"
}

if [ -n "${1+x}" ]; then
    case "$1" in
        "test")
            echo ">> Building ${app_name} tests <<"
            make_all
            echo ""
            echo ">> Running ${app_name} tests <<"
            make -C "${build_dir}" test
            ;;
        "debug")
            echo ">> Building ${app_name} debug <<"
            make_all
            ;;
        "release")
            make_clean
            echo ""
            echo ">> Building ${app_name} release <<"
            make_all "Release"
            ;;
        "run")
            target=${build_dir}/bin/${app_name}
            if [ ! -f "$target" ]; then
                echo ">> Building ${app_name} debug <<"
                make_all
                echo ""
            fi
            echo ">> Running ${app_name} <<"
            $target
            ;;
        "clean")
            make_clean
            ;;
        *)
            usage
            ;;
    esac
else
    usage
fi
