#!/usr/bin/env bash
set -euo pipefail

build_dir="$(pwd)/out"
lib_dir="lib"

usage()
{
    echo "################################################################################"
    echo "# Commands: test [lib dir], debug [lib dir], clean                             #"
    echo "# - 'Lib Dir' is the library directory inside lib/ that you wish to execute.   #"
    echo "################################################################################"
}

make_prog()
{
    echo ">> Building $1 <<"
    cmake -S . -B "${build_dir}" -DCMAKE_BUILD_TYPE="Debug" -DMY_PROG="$1"
    cmake --build "${build_dir}" -- all
}

if [ -z "${1+x}" ]; then
    usage
    exit 1
fi

if [ $1 == "test" ] || [ $1 == "debug" ]; then
    if [ -z "${2+x}" ]; then
        echo "=> ERROR: Missing second argument, library directory <="
        usage
        exit 1
    fi

    if [ ! -d "${lib_dir}/$2" ]; then
        echo "=> ERROR: Library directory does not exist in ${lib_dir}/ <="
        usage
        exit 1
    fi

    make_prog $2

    if [ $1 == "test" ]; then
        # run tests
        ${build_dir}/bin/test.out
    fi

    exit 0
fi

if [ $1 == "clean" ]; then
    echo ">> Cleaning <<"
    rm -rf "${build_dir}"
    echo "Removed ${build_dir}"

    exit 0
fi

# no matching first argument
usage
